/**
 * Seeds the database with a full, coherent demo dataset.
 *
 * ALL numeric values are SYNTHETIC, generated by a seeded PRNG so runs are
 * reproducible. Every row is flagged `isMock: true` and the UI labels the
 * dataset as demo data. Company names/tickers are real Taiwan-listed
 * identifiers, but no price, volume, indicator level, or flow figure here
 * reflects actual market data.
 *
 * Run with: npm run db:seed
 */
import { db } from "../src/lib/db";
import { SEED_INDUSTRIES } from "./seed-data";
import { DEFAULT_SCORE_WEIGHTS } from "../src/lib/scoring";
import { DEFAULT_SENTIMENT_WEIGHTS } from "../src/lib/sentiment";
import { backfillIndustryScores, classifyStockTechnicals, deriveStockStatus } from "../src/lib/jobs/compute-scores";
import { backfillIndustrySentiment } from "../src/lib/jobs/compute-sentiment";
import { utcDay, utcDayOffset } from "../src/lib/dates";
import type { StockStatus } from "../src/lib/types";

// ---------------------------------------------------------------------------
// Deterministic PRNG (mulberry32) so the demo dataset is reproducible.
// ---------------------------------------------------------------------------
let prngState = 0x9e3779b9;
function rnd(): number {
  prngState |= 0;
  prngState = (prngState + 0x6d2b79f5) | 0;
  let t = Math.imul(prngState ^ (prngState >>> 15), 1 | prngState);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
function between(min: number, max: number): number {
  return min + rnd() * (max - min);
}
function clamp(v: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, v));
}

const TRADING_DAYS = 60;
const INDICATOR_PERIODS = 16;
const SCORE_DAYS = 30;
// Sentiment history only needs to cover the trend/rank-path window the UI
// draws plus a little headroom — every extra session costs a full
// cross-industry recomputation and none of it is displayed.
const SENTIMENT_DAYS = 12;

const dayOffset = utcDayOffset;

async function main() {
  console.log("Clearing existing data...");
  // Delete in FK-safe order.
  await db.alertStock.deleteMany();
  await db.alert.deleteMany();
  await db.watchlistItem.deleteMany();
  await db.dailyBrief.deleteMany();
  await db.industrySentimentSnapshot.deleteMany();
  await db.catalyst.deleteMany();
  await db.institutionalFlow.deleteMany();
  await db.stockFundamental.deleteMany();
  await db.marketData.deleteMany();
  await db.industryScore.deleteMany();
  await db.indicatorValue.deleteMany();
  await db.indicator.deleteMany();
  await db.stock.deleteMany();
  await db.industry.deleteMany();
  await db.marketStatus.deleteMany();
  await db.scoreWeightConfig.deleteMany();
  await db.sentimentWeightConfig.deleteMany();
  await db.dataSource.deleteMany();

  const today = utcDay();

  // -------------------------------------------------------------------------
  // Data sources — every fact traces back to one of these.
  // -------------------------------------------------------------------------
  console.log("Seeding data sources...");
  const sources = await Promise.all(
    [
      {
        key: "mock-market-data",
        name: "Mock Market Data Generator",
        category: "market_data",
        description: "Synthetic OHLCV generator for MVP demo. Replace with a TWSE/TPEx adapter for live data.",
      },
      {
        key: "mock-flow",
        name: "Mock Institutional Flow Generator",
        category: "institutional_flow",
        description: "Synthetic foreign/trust/dealer net flow. Replace with a TWSE institutional-trading adapter.",
      },
      {
        key: "mock-indicator",
        name: "Mock Leading Indicator Generator",
        category: "indicator",
        description: "Synthetic indicator series (freight indices, memory prices, capex). Replace per-indicator with real sources.",
      },
      {
        key: "mock-news",
        name: "Mock Catalyst / News Generator",
        category: "news",
        description: "Illustrative catalyst headlines written for the demo. Not real news.",
      },
      {
        key: "mock-fundamental",
        name: "Mock Fundamental Generator",
        category: "fundamental",
        description: "Synthetic monthly revenue and quarterly EPS. Replace with MOPS disclosure adapter.",
      },
    ].map((s) => db.dataSource.create({ data: { ...s, isMock: true } })),
  );
  const src = Object.fromEntries(sources.map((s) => [s.key, s.id])) as Record<string, string>;

  // -------------------------------------------------------------------------
  // Configurable score weights (spec §6 defaults)
  // -------------------------------------------------------------------------
  console.log("Seeding score weight config...");
  await db.scoreWeightConfig.create({
    data: { name: "default", ...DEFAULT_SCORE_WEIGHTS, isActive: true },
  });

  console.log("Seeding sentiment weight config...");
  await db.sentimentWeightConfig.create({
    data: { name: "default", ...DEFAULT_SENTIMENT_WEIGHTS, isActive: true },
  });

  // -------------------------------------------------------------------------
  // Market status history (TAIEX)
  // -------------------------------------------------------------------------
  console.log("Seeding market status...");
  let taiex = 23100;
  const marketSeries: Array<{ date: Date; close: number; changePct: number }> = [];
  for (let i = TRADING_DAYS; i >= 0; i--) {
    const date = dayOffset(today, i);
    const changePct = between(-1.4, 1.65);
    const prev = taiex;
    taiex = taiex * (1 + changePct / 100);
    marketSeries.push({ date, close: taiex, changePct });
    await db.marketStatus.create({
      data: {
        date,
        index: "TAIEX",
        close: Math.round(taiex * 100) / 100,
        change: Math.round((taiex - prev) * 100) / 100,
        changePct: Math.round(changePct * 100) / 100,
        volume: Math.round(between(280e9, 620e9)),
        breadthAdvancers: Math.round(between(300, 700)),
        breadthDecliners: Math.round(between(250, 650)),
        foreignNet: Math.round(between(-28e6, 34e6)),
        trustNet: Math.round(between(-6e6, 11e6)),
        dealerNet: Math.round(between(-4e6, 5e6)),
        marginChange: Math.round(between(-3e6, 4e6)),
        isMock: true,
      },
    });
  }

  // -------------------------------------------------------------------------
  // Industries, stocks, indicators, values, flows, scores, catalysts
  // -------------------------------------------------------------------------
  for (const seedInd of SEED_INDUSTRIES) {
    console.log(`Seeding industry: ${seedInd.name}...`);

    const industry = await db.industry.create({
      data: {
        slug: seedInd.slug,
        name: seedInd.name,
        nameZh: seedInd.nameZh,
        description: seedInd.description,
        thesis: seedInd.thesis,
        cyclePosition: seedInd.cyclePosition,
        riskLevel: seedInd.riskLevel,
        primaryRisk: seedInd.risks[0] ?? null,
        sortOrder: SEED_INDUSTRIES.indexOf(seedInd),
      },
    });

    const bias = seedInd.strengthBias;

    // --- Indicators + historical values -----------------------------------
    for (const [idx, seedIndicator] of seedInd.indicators.entries()) {
      const indicator = await db.indicator.create({
        data: {
          industryId: industry.id,
          key: seedIndicator.key,
          name: seedIndicator.name,
          unit: seedIndicator.unit,
          description: seedIndicator.description,
          frequency: seedIndicator.frequency,
          higherIsBetter: seedIndicator.higherIsBetter,
          sortOrder: idx,
        },
      });

      const stepDays =
        seedIndicator.frequency === "daily"
          ? 1
          : seedIndicator.frequency === "weekly"
            ? 7
            : seedIndicator.frequency === "monthly"
              ? 14 // compressed so the demo shows a visible series
              : 21;

      // Effective drift is scaled by industry strength so strong industries
      // show improving indicators and weak ones show deteriorating ones.
      const effectiveDrift = seedIndicator.driftPct * (0.4 + 0.6 * ((bias + 1) / 2)) * (bias < 0 ? -0.8 : 1);

      let value = seedIndicator.baseValue;
      // Walk backwards to build a start point, then forward for the series.
      value = value / Math.pow(1 + effectiveDrift / 100, INDICATOR_PERIODS - 1);

      let previous: number | null = null;
      for (let p = INDICATOR_PERIODS - 1; p >= 0; p--) {
        const date = dayOffset(today, p * stepDays);
        const shock = (rnd() * 2 - 1) * seedIndicator.volatilityPct;
        const next = Math.max(0.01, value * (1 + (effectiveDrift + shock) / 100));
        const pctChange = previous !== null ? ((next - previous) / previous) * 100 : null;

        await db.indicatorValue.create({
          data: {
            indicatorId: indicator.id,
            date,
            value: Math.round(next * 10000) / 10000,
            previousValue: previous !== null ? Math.round(previous * 10000) / 10000 : null,
            pctChange: pctChange !== null ? Math.round(pctChange * 100) / 100 : null,
            dataSourceId: src["mock-indicator"],
            sourceUrl: null,
            dataTimestamp: date,
            isMock: true,
          },
        });

        previous = next;
        value = next;
      }
    }

    // --- Stocks + market data + fundamentals ------------------------------
    // Per-session factors SHARED by every stock in the industry. Real
    // thematic moves are correlated: when attention rotates into a group, its
    // members trade heavier and move together on the same sessions. Generating
    // each stock independently would make that pattern statistically
    // impossible, and the group-strength detector would never have anything
    // real to find.
    const sessionVolumeFactor: number[] = [];
    const sessionDriftBoost: number[] = [];
    for (let i = 0; i <= TRADING_DAYS; i++) {
      // Attention days become both more frequent and more intense for
      // industries the demo treats as strong.
      const isAttentionDay = rnd() < 0.18 + Math.max(0, bias) * 0.22;
      sessionVolumeFactor.push(isAttentionDay ? between(1.5, 2.6) : between(0.75, 1.1));
      sessionDriftBoost.push(isAttentionDay ? bias * between(0.6, 1.8) : 0);
    }

    // Per-session industry aggregates, filled in as stocks are generated, so
    // the institutional-flow history below can be derived from the price
    // action rather than invented independently of it.
    const sessionChangeSum = new Array<number>(TRADING_DAYS + 1).fill(0);
    const sessionTurnoverSum = new Array<number>(TRADING_DAYS + 1).fill(0);
    let sessionSampleCount = 0;

    const stockRecords = [];
    for (const seedStock of seedInd.stocks) {
      sessionSampleCount++;
      // Per-stock strength varies around the industry bias so the demo shows
      // leaders and laggards within the same industry.
      const stockBias = clamp(bias + between(-0.45, 0.45), -1, 1);
      const dailyDrift = stockBias * 0.42;

      const price = seedStock.basePrice / Math.pow(1 + dailyDrift / 100, TRADING_DAYS);
      const priceSeries: Array<{ date: Date; open: number; high: number; low: number; close: number; volume: number; change: number; changePct: number }> = [];

      // One base turnover level per stock, so day-to-day volume varies around
      // a stable mean instead of being redrawn from scratch each session.
      const stockBaseVolume = seedStock.basePrice > 500 ? between(1.6e6, 5e6) : between(9e6, 38e6);

      let prevClose = price;
      for (let i = TRADING_DAYS; i >= 0; i--) {
        const date = dayOffset(today, i);
        const session = TRADING_DAYS - i;
        const vol = between(-2.6, 2.6) + dailyDrift + sessionDriftBoost[session];
        const close = Math.max(0.5, prevClose * (1 + vol / 100));
        const open = prevClose * (1 + between(-0.6, 0.6) / 100);
        const high = Math.max(open, close) * (1 + between(0, 1.1) / 100);
        const low = Math.min(open, close) * (1 - between(0, 1.1) / 100);
        const volumeMultiplier =
          sessionVolumeFactor[session] * between(0.82, 1.18) * (1 + Math.max(0, stockBias) * 0.35);

        const volume = Math.round(stockBaseVolume * volumeMultiplier);
        const changePct = Math.round(((close - prevClose) / prevClose) * 10000) / 100;

        priceSeries.push({
          date,
          open: Math.round(open * 100) / 100,
          high: Math.round(high * 100) / 100,
          low: Math.round(low * 100) / 100,
          close: Math.round(close * 100) / 100,
          volume,
          change: Math.round((close - prevClose) * 100) / 100,
          changePct,
        });

        sessionChangeSum[session] += changePct;
        sessionTurnoverSum[session] += (close * volume) / 1000; // NT$ thousands

        prevClose = close;
      }

      // Classified through the SAME helper the scoring pipeline uses, so the
      // flags stored on MarketData always agree with the derived scores.
      const seriesDesc = [...priceSeries].reverse();
      const marketReturn = (marketSeries[marketSeries.length - 1].close / marketSeries[0].close - 1) * 100;
      const tech = classifyStockTechnicals(seriesDesc, marketReturn);
      const technicalTrend = tech?.trend ?? "neutral";
      const relativeStrength = tech?.relativeStrength ?? 100;
      const valuationPosition = tech?.valuationPosition ?? "mid_range";

      // Monthly revenue is generated before the stock row so the status
      // derivation can see the latest YoY growth figure.
      const revenueBase = between(1.2e6, 3.8e7);
      const monthlyRevenue = Array.from({ length: 6 }, (_, idx) => {
        const m = 5 - idx;
        const d = new Date(today);
        d.setUTCMonth(d.getUTCMonth() - m);
        const growth = stockBias * between(4, 26) + between(-8, 8);
        return {
          period: `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`,
          value: Math.round(revenueBase * (1 + (growth * (6 - m)) / 100)),
          yoyChangePct: Math.round(growth * 10) / 10,
          momChangePct: Math.round(between(-9, 14) * 10) / 10,
        };
      });
      const latestRevenueYoy = monthlyRevenue[monthlyRevenue.length - 1].yoyChangePct;

      const status = (
        tech ? deriveStockStatus(tech, latestRevenueYoy) : "high_level_consolidation"
      ) as StockStatus;

      const stock = await db.stock.create({
        data: {
          ticker: seedStock.ticker,
          name: seedStock.name,
          nameZh: seedStock.nameZh,
          exchange: seedStock.exchange ?? "TWSE",
          industryId: industry.id,
          subIndustry: seedStock.subIndustry,
          subIndustryZh: seedStock.subIndustryZh,
          status,
          mainCatalyst: seedStock.mainCatalyst,
          mainRisk: seedStock.mainRisk,
        },
      });
      stockRecords.push({ stock, stockBias, technicalTrend, relativeStrength, priceSeries });

      await db.marketData.createMany({
        data: priceSeries.map((p, i) => ({
          stockId: stock.id,
          date: p.date,
          open: p.open,
          high: p.high,
          low: p.low,
          close: p.close,
          volume: p.volume,
          change: p.change,
          changePct: p.changePct,
          relativeStrength: i === priceSeries.length - 1 ? relativeStrength : null,
          technicalTrend: i === priceSeries.length - 1 ? technicalTrend : "neutral",
          valuationPosition: i === priceSeries.length - 1 ? valuationPosition : "mid_range",
          dataSourceId: src["mock-market-data"],
          isMock: true,
        })),
      });

      await db.stockFundamental.createMany({
        data: monthlyRevenue.map((r) => ({
          stockId: stock.id,
          periodType: "monthly_revenue",
          isMock: true,
          ...r,
        })),
      });

      // Quarterly EPS (4 quarters)
      for (let q = 3; q >= 0; q--) {
        const d = new Date(today);
        d.setUTCMonth(d.getUTCMonth() - q * 3);
        const period = `${d.getUTCFullYear()}Q${Math.floor(d.getUTCMonth() / 3) + 1}`;
        const eps = Math.round(between(0.4, 9.5) * (1 + stockBias * 0.35) * 100) / 100;
        await db.stockFundamental.create({
          data: {
            stockId: stock.id,
            period,
            periodType: "quarterly_eps",
            value: eps,
            eps,
            yoyChangePct: Math.round((stockBias * between(8, 55) + between(-12, 12)) * 10) / 10,
            isMock: true,
          },
        });
      }
    }

    // --- Institutional flow: industry level + per-stock --------------------
    // Derived from the price action generated above (same approach as
    // MockInstitutionalFlowProvider) so the flow history and the price history
    // tell one consistent story. Independent noise here would routinely show
    // institutions accumulating a group that fell.
    const avgTurnover =
      sessionTurnoverSum.reduce((a, b) => a + b, 0) / Math.max(1, sessionTurnoverSum.length);

    for (let i = 20; i >= 0; i--) {
      const date = dayOffset(today, i);
      const session = TRADING_DAYS - i;
      const avgChangePct = sessionChangeSum[session] / Math.max(1, sessionSampleCount);
      const turnover = sessionTurnoverSum[session];

      const direction = clamp(avgChangePct / 1.8, -1, 1);
      const conviction = clamp(avgTurnover > 0 ? turnover / avgTurnover : 1, 0.35, 2);
      const dayBias = direction * conviction;

      const breakouts = stockRecords.filter((s) => s.technicalTrend === "breakout").length;

      await db.institutionalFlow.create({
        data: {
          date,
          scope: "industry",
          industryId: industry.id,
          foreignNet: Math.round(dayBias * between(40000, 190000)),
          trustNet: Math.round(dayBias * between(10000, 62000)),
          dealerNet: Math.round(dayBias * between(-14000, 34000)),
          marginChange: Math.round(dayBias * between(-6000, 20000)),
          turnover: Math.round(turnover || between(400000, 2600000)),
          volumeChangePct: Math.round((conviction - 1) * 1000) / 10,
          // Only meaningful for the most recent session, where the stored
          // technical flags apply; earlier sessions are left at zero rather
          // than fabricating a count the price data does not support.
          breakoutCount: i === 0 ? breakouts : 0,
          dataSourceId: src["mock-flow"],
          isMock: true,
        },
      });
    }

    for (const { stock, priceSeries } of stockRecords) {
      const avgStockTurnover =
        priceSeries.reduce((sum, p) => sum + (p.close * p.volume) / 1000, 0) / Math.max(1, priceSeries.length);

      for (let i = 6; i >= 0; i--) {
        const date = dayOffset(today, i);
        const session = TRADING_DAYS - i;
        const bar = priceSeries[session];
        if (!bar) continue;

        const turnover = (bar.close * bar.volume) / 1000;
        const direction = clamp(bar.changePct / 2.2, -1, 1);
        const conviction = clamp(avgStockTurnover > 0 ? turnover / avgStockTurnover : 1, 0.35, 2);
        const dayBias = direction * conviction;

        await db.institutionalFlow.create({
          data: {
            date,
            scope: "stock",
            stockId: stock.id,
            industryId: industry.id,
            foreignNet: Math.round(dayBias * between(6000, 68000)),
            trustNet: Math.round(dayBias * between(2000, 24000)),
            dealerNet: Math.round(dayBias * between(-4000, 12000)),
            marginChange: Math.round(dayBias * between(-2500, 7000)),
            turnover: Math.round(turnover),
            volumeChangePct: Math.round((conviction - 1) * 1000) / 10,
            dataSourceId: src["mock-flow"],
            isMock: true,
          },
        });
      }
    }

    // --- Catalysts ---------------------------------------------------------
    for (const c of seedInd.catalysts) {
      await db.catalyst.create({
        data: {
          industryId: industry.id,
          title: c.title,
          description: c.description,
          date: dayOffset(today, c.daysAgo),
          importance: c.importance,
          source: "Demo dataset (illustrative, not real news)",
          dataSourceId: src["mock-news"],
          isMock: true,
        },
      });
    }

  }

  // -------------------------------------------------------------------------
  // Score history — backfilled through the SAME derivation the daily refresh
  // uses, so week-over-week deltas measure changing conditions rather than a
  // change of formula. The seed deliberately writes no scores of its own.
  // -------------------------------------------------------------------------
  console.log(`Backfilling ${SCORE_DAYS} days of industry scores...`);
  await backfillIndustryScores(SCORE_DAYS, today);

  // Sentiment history is backfilled through the SAME derivation the daily
  // refresh uses, oldest-first, so each session's rank delta and status
  // resolve against a previous session that already exists — the whole module
  // is built on those day-over-day changes.
  console.log(`Backfilling ${SENTIMENT_DAYS} days of industry sentiment...`);
  await backfillIndustrySentiment(SENTIMENT_DAYS, today);

  // -------------------------------------------------------------------------
  // Watchlist demo entries
  // -------------------------------------------------------------------------
  console.log("Seeding watchlist...");
  const watchIndustries = await db.industry.findMany({
    where: { slug: { in: ["optical-communication", "memory", "cooling"] } },
  });
  for (const ind of watchIndustries) {
    await db.watchlistItem.create({
      data: { itemType: "industry", industryId: ind.id, note: "Monitoring for capital-flow confirmation." },
    });
  }
  const watchStocks = await db.stock.findMany({ where: { ticker: { in: ["2408", "3017", "4979", "2382"] } } });
  for (const s of watchStocks) {
    await db.watchlistItem.create({ data: { itemType: "stock", stockId: s.id } });
  }

  const counts = {
    industries: await db.industry.count(),
    stocks: await db.stock.count(),
    indicators: await db.indicator.count(),
    indicatorValues: await db.indicatorValue.count(),
    marketData: await db.marketData.count(),
    flows: await db.institutionalFlow.count(),
    scores: await db.industryScore.count(),
    sentimentSnapshots: await db.industrySentimentSnapshot.count(),
    catalysts: await db.catalyst.count(),
    watchlist: await db.watchlistItem.count(),
  };
  console.log("Seed complete:", counts);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
